name: ${name}
version: ${version}
main: com.bettermc.chickenloosefeathers.ChickenLooseFeathersPlugin
api-version: '1.21'
description: Chickens drop feathers when laying eggs
author: Vaatik

commands:
  chickenfeather:
    description: Chicken Loose Feathers commands
    usage: /<command> reload