name: ${name}
version: ${version}
main: com.bettermc.chickenloosefeathers.ChickenLooseFeathersPlugin
api-version: '26.2'
description: Chickens drop feathers when laying eggs
author: Vaatik

commands:
  chickenfeather:
    description: Chicken Loose Feathers commands
    usage: /<command> reload
    permission: chickenfeather.admin

permissions:
  chickenfeather.admin:
    description: Allows reloading the plugin configuration
    default: op
